--CREATE SEQUENCE seq_Teste01
 
-- SELECT NEXT VALUE FOR seq_Teste01

--CREATE SEQUENCE seq_Teste02
--	AS NUMERIC
--	START WITH 1
--	INCREMENT BY 1

--SELECT NEXT VALUE FOR seq_Teste02

--CREATE SEQUENCE seq_Teste03
--	AS NUMERIC
--	START WITH 100
--	INCREMENT BY -1

--SELECT NEXT VALUE FOR seq_Teste03

------- VALORES MINIMOS E MAXIMOS

--ALTER SEQUENCE seq_Teste04
--	--START WITH 1
--	INCREMENT BY 1
--	MINVALUE 1
--	MAXVALUE 1000
--	CYCLE
--	CACHE 3

--SELECT NEXT VALUE FOR seq_Teste04
-------------ALTERAR A SEQUENCE

--ALTER SEQUENCE seq_Teste04
--	RESTART WITH 100
--	MAXVALUE 10000
--	NO CACHE

------CONSULTAR SEQUENCES

--SELECT last_used_value, * FROM sys.sequences
--WHERE NAME = 'seq_Teste04'

------REINICIAR UMA SEQUENCE

--ALTER SEQUENCE seq_Teste04 RESTART WITH 100

--SELECT NEXT VALUE FOR seq_Teste04