CREATE TRIGGER tgr_AjustaSaldo
ON TbVendas
FOR INSERT
AS
BEGIN 
	DECLARE @QUANTIDADE   INT
	DECLARE @DATA		 DATETIME
	DECLARE @PRODUTO     VARCHAR(10)

	SELECT @DATA = DATA, @QUANTIDADE = QUANTIDADE, @PRODUTO = PRODUTO FROM INSERTED
	
	UPDATE tbSaldos
		SET SALDO_FINAL = SALDO_FINAL - @QUANTIDADE,
		DATA_ULT_MOV = @DATA
		WHERE PRODUTO = @PRODUTO


	INSERT INTO tbHistoricoVendas (PRODUTO, QUANTIDADE, DATA_VENDA)
	VALUES (@PRODUTO, @QUANTIDADE, @DATA)


END
GO